# План:
1. Python
2. Numpy
3. Pandas
4. Regexp + regexp with dataframes
5. Texts
6. Matplotlib, Seaborn
7. Classification, clustering, binary, multiclass, multilabel
8. Metrics
9. Feature extraction
10. Pyspark/sql

In [ ]:
! pip install numpy

<img src="gifs/start.gif" width="400">

# Python

* Целая куча упражнений на типы данных\операторы и функции

https://www.w3resource.com/python-exercises/

Типы данных:
    * Числа (7382, 3.14, 3+4j, Decimal, Fraction)
    * Строки ('net', "your's", u'радость')
    * Списки ([1, [2, 'three'], 4])
    * Словари ({'Alex': 2, 'Brian': 4})
    * Кортежи ('Leo', 21.7, 'single')
    * Множества (set(1,2,3), {'a', 'b', 'c'})
    * Файлы (open('myfile', 'r'))

1. Склеить 3 подстроки "ada", "lovelace", "was considered the world's first computer programmer.". Первые две строки сделать с большой буквы.  (★☆☆)

In [160]:
s1 = 'ada '
s2 = 'lovelace'
s3 = " was considered the world's first computer programmer. "
s1 = s1.title()
s2 = s2.title()
print(s1+s2+s3)

Ada Lovelace was considered the world's first computer programmer. 


2. Удаление лишних пробельных символов справа, слева, с обоих сторон  (☆☆☆)

In [162]:
print(s3.lstrip())
print(s3.rstrip())
print(s3.strip())

was considered the world's first computer programmer. 
 was considered the world's first computer programmer.
was considered the world's first computer programmer.


3. Найти первое вхождение в строку подстроки (☆☆☆)

In [168]:
s1="But if you stick with me, I’m gonna accomplish great things, Morty, and you’re gonna be part of ’em."
s2="you"

s1.find(s2)

7

* isdigit - состоит ли строка из цифр;
* isalpha - состоит ли строка из букв;
* isalnum - состоит ли строка из цифр или букв;
* islower - состоит ли строка из символов в нижнем регистре;
* isupper - состоит ли строка из символов в верхнем регистре;
* istitle - начинаются ли слова в строке с заглавной буквы.

4. Разбить строку по разделителю (☆☆☆)

In [171]:
s1="Holy#cow,#Rick!#I#didn’t#know#hanging#out#with#you#was#making#me#smarter!"

S = s1.split('#')
print(S)

['Holy', 'cow,', 'Rick!', 'I', 'didn’t', 'know', 'hanging', 'out', 'with', 'you', 'was', 'making', 'me', 'smarter!']


5. Полученный массив строк склеить через пробел (★☆☆)

In [176]:
for i in S:
        print(i, end=' ')

Holy cow, Rick! I didn’t know hanging out with you was making me smarter! 

6. Вывести данные из словаря в три строки в виде "NAME (age AGE) is a JOB" (★☆☆)

(hint: .format())

In [223]:
personal_data = {1: ("Ann", 29, "Artist"), 
               2: ("Leo", 54, "Programmer"), 
               3: ("Tiffany", 43, "Shop Assistant")}

P = personal_data.values()
for l in P:
        print(l[0],"(age",l[1],") is a",l[2])

Ann (age 29 ) is a Artist
Leo (age 54 ) is a Programmer
Tiffany (age 43 ) is a Shop Assistant


7. Требуется определить, является ли данный год високосным. (год является високосным, если его номер кратен 4, но не кратен 100, а также если он кратен 400.)  (★★☆)

Входные данные: Вводится единственное число - номер года (целое, положительное, не превышает 30000).

Выходные данные: Требуется вывести слово YES, если год является високосным и NO - в противном случае.

In [229]:
yeear = int(input())
if yeear%4 == 0 and yeear%100 != 0 or  yeear%400 == 0:
    print("YES")
else:
    print("NO")

2019
NO


8. Закодируйте каждый элемент списка слов числом, результат сопоставления (слово-число) поместите в словарь.  (★☆☆)

In [142]:
words = ['Not', 'my', 'cup', 'of', 'tea']
hzzzz

'Not'

9. Удалить второй элемент из списка по индексу\по значению  (★☆☆)

In [244]:
dogs = ['border collie', 'australian cattle dog', 'labrador retriever']

del dogs[1]
dogs

['border collie', 'labrador retriever']

10. Вывести срез списка с 3 по 5 элемент включительно и все слова перевести в верхний регистр (★☆☆)

In [268]:
dogs = ['border', 'collie', 'australian', 'cattle', 'dog', 'labrador', 'retriever']
dog = dogs[3:6]

for i in dog:
    dog = i.title()
    print(dog)

Cattle
Dog
Labrador


11. Словарь словарей. Вывести из словаря для каждого питомца его имя, породу, имя владельца, и наличие прививки. Строку вывода формировать через .format() (★☆☆)

In [24]:
pets = {'willie': {'kind': 'dog', 'owner': 'eric', 'vaccinated': True},
        'walter': {'kind': 'cockroach', 'owner': 'eric', 'vaccinated': False},
        'peso': {'kind': 'dog', 'owner': 'chloe', 'vaccinated': True},
        }
'Willie: {}, Walter: {}, Peso: {}'.format(pets['willie'],pets['walter'],pets['peso'])

"Willie: {'kind': 'dog', 'owner': 'eric', 'vaccinated': True}, Walter: {'kind': 'cockroach', 'owner': 'eric', 'vaccinated': False}, Peso: {'kind': 'dog', 'owner': 'chloe', 'vaccinated': True}"

12. Проверить является ли множество подмножеством другого множества  (★☆☆)

In [276]:
a=set([2, 5, 6])
b=set([2, 4, 8, 3, 5, 6])

a.issubset(b)

True

13. Объединить несколько множеств (★☆☆)

In [282]:
a=set([10, 35, 6, 5])
b=set([2, 4, 8, 3, 5, 6, 35])
q=set([4, 5, 35])

a.union(q,b)

{2, 3, 4, 5, 6, 8, 10, 35}

14. Посчитать пересечение множества b с остальными из предыдущего задания  (★★☆)

(hint: set.intersection(other, ...) (или set & other &) )

In [283]:
b.intersection(a,q)

{5, 35}

15. Вывести множество из элементов, встречающихся в одном множестве, но не встречающиеся в обоих. (★★☆)

(hint: .symmetric_difference())

In [284]:
a=set([1, 2, 3, 4, 5])
b=set([3, 4, 5, 6, 7])

a.symmetric_difference(b)

{1, 2, 6, 7}

16. Предположим, есть файл с данными клиентов. В качестве простого примера воьзьмем txt-файл следующего содержания:

    lastname,age,debt,occupation
    
    Adrianov,25,30000,artist
    
    Нужно считать файл data/credit_sample.txt.
    Сделать словарь вида:
        {lastname: (age,debt,occupation)}
    
    Посчитать сколько уникальных профессий получилось в словаре.
    
    Результат записать в json (★★★)

In [39]:
newfile = open('file_new', 'w')
with open('data/credit_sample.txt') as file:
    for line in file:
        s = line.replace(',',' ')
        newfile.write(s)

f = {}
n = 1

with open('file_new') as file:
    for i, line in enumerate(file):
        if i >= n:
            key, *value = line.split()
            f[key] = value
print(f)

list =[]
for val in f.values(): 
  if val in list: 
    continue 
  else:
    list.append(val)

print(list)

{'Adrianov': ['25', '30000', 'artist'], 'Belkin': ['42', '4000', 'programmer'], 'Koltunov': ['32', '100', 'sportsman'], 'Loptev': ['25', '30000', 'artist'], 'Bobrov': ['42', '4000', 'programmer'], 'Karelin': ['32', '100', 'sportsman']}
[['25', '30000', 'artist'], ['42', '4000', 'programmer'], ['32', '100', 'sportsman']]


### os, sys, datetime

17. Получить список файлов в папке gifs/ и оставить только файлы с расширением .gif (★★☆)

In [91]:
import os
for file in os.listdir('gifs'):
    if file.endswith('.gif'):
        print(file)

start.gif
journey.gif
bender.gif
inprogress.gif


18. Создать папку с названием temp и удалить её (★☆☆)

In [332]:
path = "temp"    
os.mkdir(path)

In [333]:
os.rmdir(path)

19. Вывести переменные среды (★☆☆)

(hint: environ)

In [335]:
print(os.environ)

environ({'CONDA_SHLVL': '1', 'LS_COLORS': 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv

20. Как игнорировать warrnings?

* Про datetime и timedelta 

https://www.guru99.com/date-time-and-datetime-classes-in-python.html

21. Вывести сегодняшнюю, вчерашнюю и завтрашнюю дату (☆☆☆)

In [2]:
from datetime import datetime, timedelta, date
t = datetime.today()
h = timedelta(days = 1)
y = t - h
tw = t + h
print(y)
print(t)
print(tw)

2019-12-05 08:25:38.193954
2019-12-06 08:25:38.193954
2019-12-07 08:25:38.193954


22. Вывести день недели сегодняшней даты (★☆☆)

In [138]:
datetime.isoweekday(t)

4

23. Получить список дат за предыдущую неделю (★★☆)

In [4]:
for i in range(0,7):
    cheburek = timedelta(days = i + datetime.isoweekday(t))
    days = date.today() - cheburek
    print(days)

2019-12-01
2019-11-30
2019-11-29
2019-11-28
2019-11-27
2019-11-26
2019-11-25


24. Вывести дату с часами и минутами, отформатировать в формате: 01.12.2019 00:12:54 (★★☆)
            
(hint: now().strftime())

In [132]:
t.strftime('%m.%d.%Y %H:%M:%S')

'12.05.2019 22:01:38'

25. Исходя из текущей даты вычислить дату предыдущего понедельника (★★★)

In [139]:
we = timedelta(weeks = - 1, days = - datetime.isoweekday(t) + 1)
mon = t + we
print(mon)

2019-11-25 22:01:38.497384


# Numpy

### numpy в картинках (реально лучший):

https://jalammar.github.io/visual-numpy/

In [6]:
import numpy as np

1. Задать нулевой вектор размером 10 (★☆☆)

(hint: np.zeros)

In [10]:
z = np.zeros(10)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

2. Как найти размер занимаемой памяти любым массивом (★☆☆)

(hint: size, itemsize)

In [8]:
z.size

10

In [9]:
z.itemsize

8

3. Создать вектор из 10 нулей, кроме пятого элемента, который равен 1 (★☆☆)

In [12]:
one = np.zeros(10)
one[5] = 1
one

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

4. Создать вектор от 10 до 50 включительно (★☆☆)

(hint:np.arange)

In [17]:
a = np.arange(10,51)

5. Перевернуть вектор (первый элемент будет последним) (★☆☆)

In [22]:
a[::-1]

array([50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34,
       33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17,
       16, 15, 14, 13, 12, 11, 10])

6. Создать матрицу 3х3 с элементами от 0 до 8 (★☆☆)

(hint: reshape)

In [26]:
b = np.arange(9)
b.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

7. Найти индексы не нулевых эемелентов в numpy array [1,2,0,0,4,0] (★☆☆)

(hint: np.nonzero)

In [30]:
c = np.array([1,2,0,0,4,0])
print(np.nonzero(c))

(array([0, 1, 4]),)


8. Создать матрицу 10x10 array с рандомными числами и найти минимум, максимум и среднее (★☆☆)

In [108]:
d = np.random.random((10,10))
print(d)
print("Maximum = ", np.max(d))
print("Minimum = ", np.min(d))
print("Mean = ", np.mean(d))

[[0.15994994 0.48759214 0.58673181 0.8489948  0.4979289  0.79576131
  0.41956332 0.09563576 0.36392492 0.80830322]
 [0.37788919 0.27921726 0.97449075 0.21932132 0.02116567 0.32832055
  0.38093536 0.88568751 0.3566113  0.3260133 ]
 [0.64353042 0.38237015 0.39816778 0.32244735 0.64812904 0.18591992
  0.36462645 0.17683188 0.8257539  0.72682573]
 [0.85576798 0.29010133 0.29937209 0.88606717 0.34467456 0.12669749
  0.44602747 0.58703305 0.72262413 0.48573741]
 [0.36125408 0.9735027  0.73452354 0.8622245  0.63340292 0.48772839
  0.57088879 0.73342728 0.49985073 0.62261323]
 [0.96433959 0.04660307 0.09684119 0.78841107 0.91703928 0.90732463
  0.35429626 0.83428096 0.84213495 0.10220594]
 [0.59640648 0.11464886 0.42679297 0.33674021 0.28588207 0.30678834
  0.24632436 0.7603097  0.606188   0.91925727]
 [0.9113526  0.81617416 0.70098542 0.71357403 0.7728034  0.07973803
  0.23866059 0.68013993 0.66108495 0.03414113]
 [0.60074645 0.68954246 0.16556696 0.30040682 0.2437618  0.34760545
  0.47735596

9. Создать матрицу 8x8 и заполнить 0 и 1 в стиле шахматной доски (★☆☆)

(hint: array[::n])

In [142]:
kek = np.zeros((8,8))
kek[0::2,0::2] = 1
kek[1::2,1::2] = 1
kek

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

10. Нормализовать рандомную матрицу 5x5 (★☆☆)

(hint: (x - mean) / std)

In [47]:
f = np.random.random((5,5))
(f-np.mean(f))/np.std(f)

array([[ 0.85906129, -0.58800986,  1.4389594 , -1.42862747, -0.2700278 ],
       [ 0.44415547, -0.02914952, -1.17168382, -0.18580471,  0.44864599],
       [ 1.68469618, -0.23687396,  1.68776793,  1.54898776,  0.97761695],
       [ 0.04564665, -0.83457014, -1.47658527,  0.06454069, -1.43786154],
       [-1.07037411,  0.29017678, -1.52666199,  0.48918232,  0.27679279]])

11. Найти общие элементы между двумя массивами

(hint: np.intersect1d)

In [48]:
np.intersect1d(c,one)

array([0., 1.])

12. Извлечь целую часть рандомного массива чисел различными способами (максимум 5) (★★☆)

In [43]:
a = np.random.uniform(2, 8, (10))
# a.astype(int)

TypeError: only size-1 arrays can be converted to Python scalars

13. Создать рандомный вектор размера 10 и отсортировать его (★★☆)

In [54]:
e = np.random.random(10)
print(np.sort(e))

[0.07362361 0.18765833 0.19468567 0.35881699 0.40837204 0.55313578
 0.6211777  0.77810862 0.86655838 0.97576619]


14. Проверить одинаковы ли два рандомных массива А и B (★★☆)

(hint: np.allclose, np.array_equal)

In [69]:
A = np.random.rand(10)
B = np.random.rand(10)
print(A)
print(B)
np.array_equal(A,B)

[0.44000481 0.42244925 0.24993632 0.4553637  0.59689669 0.8336787
 0.30899027 0.04768328 0.84448274 0.30154856]
[0.46080582 0.39034466 0.73639165 0.30806164 0.96901094 0.21909708
 0.25380463 0.25832796 0.43706285 0.19093511]


False

15. Создать рандомный ветор размером 10 и максимальный элемент заменить на -1 (★★☆)

(hint: argmax)

In [9]:
p = np.random.random(10)
print(p)
print(np.argmax(p))
p[np.argmax(p)] = -1
print(p)

[0.92031119 0.48628596 0.20403001 0.27982763 0.55255807 0.42839039
 0.39917701 0.1401623  0.10147368 0.42270765]
0
[-1.          0.48628596  0.20403001  0.27982763  0.55255807  0.42839039
  0.39917701  0.1401623   0.10147368  0.42270765]


16. Найдите самый близкий элемент к данному рандомному числу в векторе? (★★☆)

(hint: argmin)

In [168]:
Z = np.arange(10)
v = np.random.uniform(0,10)
print(Z)
print(v)
index =  v/Z
index.astype(float) 
print(index)
# print(Z[index])
# index.argmin()


[0 1 2 3 4 5 6 7 8 9]
4.96309302236046
[       inf 4.96309302 2.48154651 1.65436434 1.24077326 0.9926186
 0.82718217 0.70901329 0.62038663 0.55145478]


/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:5: RuntimeWarning: divide by zero encountered in true_divide
  """


17. Посчитать среднее для каждой строки матрицы (★★☆)

In [107]:
Z = np.arange(100)
K = Z.reshape(10,10)
print(K)
np.mean(K[:,:10], axis = 1)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


array([ 4.5, 14.5, 24.5, 34.5, 44.5, 54.5, 64.5, 74.5, 84.5, 94.5])

18. Посчитать среднее со скользящим окном над массивом (★★★)

(hint: np.cumsum)

In [120]:
np.cumsum(K)
hzzzz

NameError: name 'hzzzz' is not defined

<img src="gifs/bender.gif" width="400">

# Regular expressions

* Cупер статья на все времена. Особенно понятно все про такие сложные штуки как lookaround. 

https://habr.com/ru/post/349860/

* На этом сайте удобно тестировать регулярку, которую мучаешь, можно написать несколько примеров и тестировать на них. Важно не забывать выбирать Python:

https://regex101.com/

* Задания на регулярки, начинай с того, которое уже кажется сложным, можешь запихнуть их в этот ноутбук)

https://regexone.com/

1. Из строки в файле data/rejson.txt вытащить хэш. Пример:

'master_guid': '<b>233880bb4c50d247f84edc9cac9e6e29</b>_2308194320'

In [169]:
import re
reg = open('data/rejson.txt')


# Pandas

* Pandas в картинках

https://jalammar.github.io/gentle-visual-intro-to-data-analysis-python-pandas/

* 10 minutes to pandas

https://pandas.pydata.org/pandas-docs/stable/getting_started/10min.html

* 🐼реально классный твиттер чувака с крутыми pandas tricks:
    
https://mobile.twitter.com/i/moments/1158828895547854849

<img src="gifs/inprogress.gif" width="400">